### ISSUE TITLE
A12 - Freecodecamp - CSS Grid

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#110]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a12-freecodecamp-css-grid.md

**Comment by CamilaSarmiento1** [comment]
Buenos dias @Angelbt12 , agradezco me compartas el resultado del ejercicio realizado

**Comment by CamilaSarmiento1** [comment]
@Angelbt12 Adjuntar imagen de culminación del ejercicio

**Comment by Angelbt12** [comment]
![image](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/6cc35d66-50f4-4712-8910-decbef14f55a)
