### ISSUE TITLE
Opcional - A26 - Freecodecamp - Nutrition Labe

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#152]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a26-freecodecamp-nutrition-label.md

**Comment by Angelbt12** [comment]
![image](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/ab9a39c4-2d86-4890-a884-446ccd1c2979)
