### ISSUE TITLE
Opcional A26 - Freecodecamp - Nutrition Labe

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#153]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a26-freecodecamp-nutrition-label.md

**Comment by Brandonz07** [comment]
![Image](https://github.com/selsa-inube/bootcamp-apr/assets/165967324/cb1b2c42-e4e2-4405-8481-53f4e5d2c91b)
