### ISSUE TITLE
Opcional A25 - Freecodecamp - Survey Form

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#158]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content//html-css/a25-freecodecamp-survey-form.md

**Comment by Angelbt12** [comment]
![Image](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/444301ab-5071-4376-b28b-873a4f865826)
