### ISSUE TITLE
Opcional - a14-freecodecamp-intermediate-algorithm-scripting.md

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#227]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/js/a14-freecodecamp-intermediate-algorithm-scripting.md

**Comment by Brandonz07** [comment]
![Image](https://github.com/selsa-inube/bootcamp-apr/assets/165967324/6405e0a5-d473-4dc5-9362-caa38c4c8a23)
