### ISSUE TITLE
A7 - Freecodecamp - Cat Photo App

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#64]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content//html-css/a7-freecodecamp-cat-photo-app.md

**Comment by CamilaSarmiento1** [comment]
Buenos dias @Angelbt12 , agradezco puedas compartirme la imagen que te muestra el sistema cuando completas la unidad es similar a la que te comparto a continuación 

![Image](https://github.com/selsa-inube/bootcamp-apr/assets/164539682/ec5ac387-6a12-453b-aeb6-f4b36b4e7b55)

**Comment by Angelbt12** [comment]
![imagen_2024-04-17_084604489](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/9ef0940e-f729-44f5-89eb-389ad14913db)
