### ISSUE TITLE
A7 - Freecodecamp - Cat Photo App

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#65]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content//html-css/a7-freecodecamp-cat-photo-app.md

Entregable : Adjuntar imagen de culminación del ejercicio

**Comment by Brandonz07** [comment]
![Image](https://github.com/selsa-inube/bootcamp-apr/assets/165967324/a15abfdf-4a75-426b-a81e-0585a05864bc)
