### ISSUE TITLE
A6 - Selectors without Classes and Ids

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#71]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content//html-css/a6-selectors-without-classes-and-ids.md

Entregable : Adjuntar imagen de culminación del ejercicio

**Comment by luisalejandrosalazar** [comment]
Please review and answer my PR comments.

"_Over all, good job

Just, avoid use of hr tag, instead stylize container borders, please refactor it._"
