### ISSUE TITLE
A8 - Freecodecamp - Cafe Menu

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#78]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a8-freecodecamp-cafe-menu.md

**Comment by Angelbt12** [comment]
![imagen_2024-04-17_084705776](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/ae4d7e7f-7a16-4c4b-b127-9fe37ac1d788)
