### ISSUE TITLE
A8 - Freecodecamp - Cafe Menu

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#79]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a8-freecodecamp-cafe-menu.md

Entregable : Adjuntar imagen de culminación del ejercicio

**Comment by Brandonz07** [comment]
![Image](https://github.com/selsa-inube/bootcamp-apr/assets/165967324/c9fe41eb-00a5-4a97-ae21-bd0f87d4d8bd)
