### ISSUE TITLE
A11 - Freecodecamp - Photo Gallery

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#84]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a11-freecodecamp-photo-gallery.md

**Comment by Angelbt12** [comment]
![image](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/c3384198-8b0b-46e7-9d27-a3a23cfac97c)

**Comment by Angelbt12** [comment]
![image](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/9b7d9dda-3b32-4cc9-9277-9fe85ac01ee8)
