### ISSUE TITLE
A10 - Freecodecamp - CSS Flexbox

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#95]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a10-freecodecamp-css-flexbox.md

**Comment by CamilaSarmiento1** [comment]
Buenos dias @Angelbt12 , agradezco me compartas el resultado del ejercicio realizado

**Comment by CamilaSarmiento1** [comment]
@Angelbt12 Adjuntar imagen de culminación del ejercicio

**Comment by Angelbt12** [comment]
![image](https://github.com/selsa-inube/bootcamp-apr/assets/125980817/b635b9f4-bdf0-4352-9468-5aba7326dc4d)
