### ISSUE TITLE
A10 - Freecodecamp - CSS Flexbox

### ISSUE THREAD

**Issue by CamilaSarmiento1** [selsa-inube/bootcamp-apr#96]
https://github.com/selsa-inube/bootcamp-apr/blob/main/content/html-css/a10-freecodecamp-css-flexbox.md

Entregable : Adjuntar imagen de culminación del ejercicio

**Comment by Brandonz07** [comment]
![Image](https://github.com/selsa-inube/bootcamp-apr/assets/165967324/2c90c1e1-eba5-4a93-9de8-78ebc2ae5412)
